[build]
target = ["aarch64-linux-android","x86_64-linux-android"]

[target.aarch64-linux-android]
rustflags = ["-C", "target-feature=+crt-static"]


[target.x86_64-linux-android]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-unknown-linux-gnu]
